# Generated by Django 4.2.4 on 2023-08-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mushrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('user', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
